# Conclusion

## Results

Through this report, we managed to make the survey data stand out using graphs and plots. Additionally, we observed connections among multiple factors within responses, which is difficult to see with raw data alone. An interesting aspect of the survey was the diversity of the questions asked to individual respondents, which enabled us to display links between factors.

However, our analysis was constrained by the relatively small dataset of 2,487 rows. Consequently, when we examine particular demographics, such as regional origins, in our research, our findings lack certainty due to the small number of people we studied, which makes it hard to determine if our findings are statistically significant or merely random occurrences.

## Recommendations to Vaud Promotion

Looking at the observed results, have found several recommendations that we could propose to Vaud Promotion in order to better promote and target their promotion to travelers coming to Vaud.

To begin with, despite only having 8% of travelers in the survey having taken a package, the main target for the packages proposition are people from Asia, followed by Africa and South America. So, to promote the packages, these are the targets that are willing to spend more to obtain packages which includes some other expenses category. Also, the travelers coming with a package seem to spend the least (link to unknown people).

Next, the American are the tourists that spend the most when looking at individual expenses. They seem to spend a lot in any category and pretty much everywhere in Vaud. Also, most of the overall expenses are done in the Riviera-Pays-d'Enhaut district, with a record of 2'500 CHF on average per person, followed by Lausanne with 2'300 CHF. The rest have records of between 1'500 to 2'000 CHF of spendings. So, if the company wants to propose packages, the Riviera-Pays-d'Enhaut could be a great target for them as there is a lot of spending in this district.

Then, looking at seasonality of the travelers, it seems that most of the respondents come in the seasons of March and July, which is logical especially as it is the summer. Also, if the company wants to focus on promoting a specific district for the winter, Aigle is the most frequented district in winter.

After that, we can focus on the groups. 68% of the travelers coming to Vaud are accompanied by their partners, which is an indication that Vaud is a good canton to promote people coming with their partner. Now, by looking at the expenses, solo travelers spend more on average per personne that families or groups, with respective spendings of 3'300 CHF for solo travelers, 2'700 CHF for families and 2'200 CHF for friend groups.

Looking at the destinations and accomodations, majority of travelers spend only 1 night in Vaud. The most popular accomodations are hotels, followed by stays with relatives or friends or even rented apartments such as AirBnB. Moreover, on a whole trip, travelers stay in general between 10 to 25% in Switzerland.

Finally, when looking at the origins of the travelers, 72% of the Swiss tourists coming to Vaud are Swiss-German. Swiss-French represent 24% and residents of Vaud coming as tourists only 4%. Focusing on the Swis-German tourists, looking at relative inhabitants per canton, most people come from Uri. Also, among the visitors of the Jura-Nord Vaudois district, 60% are Swiss-German. Finally, among the visiors of Aigle, 28% are from the French speaking part of Switzerland.


## Improvements for future works

After finishing the project, we identified points for improvement in some aspects of the survey. We will provide some suggestions for improvement for future projects with the company.

To begin with, it could be of interest to obtain more data in terms of quantity to have better representations of the origins of people specifically. This way, we could better identify specific regions of origin instead of countries of origin. It is difficult to prove that our findings are statistically significant when the number of respondents is so low. The surveys need to be conducted uniformly throughout time and locations.

Also, it would be interesting to add certain aspects to the survey, such as the date of the respondent's answer and the birth date or age of the respondent, in order to push some analyses further. Also, the open questions can be tricky to analyze, as there were some questions where people didn't really understand the question or where people made some mistakes, which is more difficult to handle when doing an analysis. For example, as a recommendation to avoid outliers in spending, it could be interesting to provide a range of prices to select from instead of letting the respondent answer freely, as we had the case of people responding in their own currency instead of CHF, which biased the responses. Finally, it could be interesting to have more details on what is provided in the packages for travelers.
