# Data
```{r, output = FALSE}
source(here::here("scripts", "setup.R"))
```

```{r}
questions <- data.frame(
  "Questions Asked" = c("id of the Observation",
                        "Continent",
                        "Land",
                        "Region",
                        "Subregion",
                        "F12: Start of holidays in Switzerland:",
                        "F13: End of holidays in Switzerland:",
                        "Q15: What time of year was in Switzerland during your holidays?",
                        "Q16: Type of holiday:",
                        "F20: Number of overnight stays in Switzerland:",
                        "Q21: How long did your tour of Europe take in total (including Switzerland)?",
                        "Q30: Have you booked a package tour (a bundling of arrival and departure, accommodation and/or other tourist services on site)?",
                        "Alone",
                        "With partner",
                        "With friends / acquaintances",
                        "With children",
                        "With other family members",
                        "In a group with unknown people",
                        "With one dog(s)",
                        "With one or more other pet(s)",
                        "F32: Size of your group (number of people including yourself):",
                        "F33: Size of your group (number of people including yourself but excluding people you don't know):",
                        "Auxiliary variable: Difference of F13 end of holiday CH minus F12 start of holiday CH plus 1",
                        "Auxiliary variable: Number of persons from F32 / F33 travel group",
                        "Q80: Please select a currency for your details:",
                        "Q80: Please select a currency for your details. - Others, namely:",
                        "Q81: How much did you spend in total during your stay in Switzerland? -Overnight stay:",
                        "Q81: How much did you spend in total during your stay in Switzerland? - Without arrival and departure: train, mountain railway, boat and other public transport:",
                        "Q81: How much did you spend in total during your stay in Switzerland? - Food & drink: in the accommodation, on the road, out and about:",
                        "Q81: How much did you spend in total during your stay in Switzerland? - Souvenirs, gifts, watches, jewellery:",
                        "Q81: How much did you spend in total during your stay in Switzerland? - Other shopping:",
                        "Q81: How much did you spend in total during your stay in Switzerland? - Other expenses:",
                        "Q81: How much did you spend in total during your stay in Switzerland? -Total:",
                        "Q82: How much did you spend in total during your stay in Switzerland? -Package:",
                        "Q82: How much did you spend in total during your stay in Switzerland? -Overnight stay:",
                        "Q82: How much did you spend in total during your stay in Switzerland? - Without arrival and departure: train, mountain railway, boat and other public transport:",
                        "Q82: How much did you spend in total during your stay in Switzerland? - Food & drink: in the accommodation, on the road, out and about:",
                        "Q82: How much did you spend in total during your stay in Switzerland? - Souvenirs, gifts, watches, jewellery:",
                        "Q82: How much did you spend in total during your stay in Switzerland? - Other shopping:",
                        "_Q82: How much did you spend in total during your stay in Switzerland? - Other expenses:__",
                        "Q82: How much did you spend in total during your stay in Switzerland? - Total expenditure excluding expenditure on package holidays",
                        "Q83: Does the package include travel to and from the resort?",
                        "Q85: You have therefore spent a total of [amount] (excluding package costs) during your stay in Switzerland. Is that right?",
                        "Q105: Your resort where you were staying when your email address was collected for this survey:",
                        "Q105: Your resort where you were staying when your email address was collected for this survey. - Other resort:",
                        "Q105: Your resort where you were staying when your email address was collected for this survey. -Code:",
                        "Q105: Your resort where you were staying when your email address was collected for this survey. - Organization Code:",
                        "Q125: Your accommodation:",
                        "Q125: Your accommodation: Other, namely:",
                        "F130: Star category of the hotel / spa house visited:",
                        "F130: Star category of the hotel / spa house visited: Other classification, namely:",
                        "Q135: Number of nights in [Answer from F105]:",
                        "Winter - Summer (average of arrival and departure date with limit end of April / beginning of May)",
                        "___",
                        "___",
                        "___",
                        "___"),
  "Code Number" = c("Serial2",
                    "F05_01",
                    "F05_02",
                    "F05_03",
                    "F05_04",
                    "F12",
                    "F13",
                    "F15",
                    "F16",
                    "F20",
                    "F21",
                    "F30",
                    "F31_01",
                    "F31_02",
                    "F31_03",
                    "F31_04",
                    "F31_05",
                    "F31_06",
                    "F31_07",
                    "F31_08",
                    "F32",
                    "F33",
                    "hHoliday Duration",
                    "hGroupPeople",
                    "F80",
                    "F80_a05",
                    "F81_01",
                    "F81_02",
                    "F81_03",
                    "F81_04",
                    "F81_05",
                    "F81_06",
                    "F81_Total",
                    "F82_01",
                    "F82_02",
                    "F82_03",
                    "F82_04",
                    "F82_05",
                    "F82_06",
                    "F82_07",
                    "F82_Total",
                    "F83",
                    "F85",
                    "F105",
                    "F105A",
                    "F105_Code",
                    "F105_OrgCode",
                    "F125",
                    "F125_a11",
                    "F130",
                    "F130_a07",
                    "F135_01",
                    "F12_F13_Mittelwert_2Cat_final",
                    "___",
                    "___",
                    "___",
                    "___"),
  "Data Type" = c("None",
                  "{1, Europe}...",
                  "{1, Australia}...",
                  "{1, Australian Capital Territory}...",
                  "{1, Barking and Dagenham}...",
                  "None",
                  "None",
                  "{1, Winter}...",
                  "{1, Holidays with only one overnight stay in Switzerland}...",
                  "None",
                  "None",
                  "{1, Yes}...",
                  "{1, True}...",
                  "{1, True}...",
                  "{1, True}...",
                  "{1, True}...",
                  "{1, True}...",
                  "{1, True}...",
                  "{1, True}...",
                  "{1, True}...",
                  "{1, 1}...",
                  "{1, 1}...",
                  "None",
                  "None",
                  "{1, CHF}...",
                  "None",
                  "None",
                  "None",
                  "None",
                  "None",
                  "None",
                  "None",
                  "None",
                  "None",
                  "None",
                  "None",
                  "None",
                  "None",
                  "None",
                  "None",
                  "None",
                  "{1, Yes}...",
                  "{1, Yes}...",
                  "None",
                  "None",
                  "{1, Aarau}...",
                  "{1, aarau-info}...",
                  "{1, Hotel / Kurhaus}...",
                  "None",
                  "{1, *}...",
                  "None",
                  "None",
                  "{0, Winter}...",
                  "___",
                  "___",
                  "___",
                  "___"))
```


```{r}
library(knitr)
library(kableExtra)

questions %>%
  kbl(caption = "Questions asked during the Survey") %>%
  kable_paper("striped", full_width = F) %>%
  pack_rows("Q5: Permanent residence", 2, 5) %>%
  pack_rows("Q31: Who did you travel with?", 13, 20)
```

## Présentation des données

## Tableau avec résumé des données