# Introduction

The object of this report is the tourism survey conducted by Tourismus Monitor Schweiz, focusing on tourists visiting the canton of Vaud, Switzerland, from November 2022 to March 2024. The survey aims to identify key information about tourists visiting Vaud, including information about their stay in Switzerland (length of stay, amount spent, etc.) and information identifying the tourists (Country of origin, type of visit, etc.). The survey also provides information on the specific destination within the canton (City, hotel, etc.).

Our report aims to simplify the comprehension of this raw data through data visualization techniques and plots. Additionally, we aim to categorize the types of tourists visiting Vaud and their regions of origin. This will help Vaud Plus in understanding the demographics of visitors to the canton and possibly help with targeted marketing efforts.

The first part of our report presents the data in a more readable format. Following that, we conduct exploratory data analysis (EDA), which involves creating basic charts to provide perspective and convey the scale of the variables to the reader. Next, we proceed to the analysis phase, where we cross-analyze multiple variables to highlight correlations. The final section of the report is dedicated to plotting various variables on a map of the districts of Canton Vaud. Lastly, we will articulate our conclusions about the survey data and share our experience with this report.